### ISSUE TITLE
to haskell-ghc-mod or not to haskell-ghc-mod?

### ISSUE THREAD

**Issue by cblp** [atom-haskell/autocomplete-haskell#10]
> autocomplete-haskell is already using backend haskell-ghc-mod, and new backend haskell-ghc-mod appeared. You can select one in autocomplete-haskell settings. Will keep using haskell-ghc-mod for now.

Does it say it uses haskell-ghc-mod instead of haskell-ghc-mod?

**Comment by lierdakil** [comment]
Apparently it does. This probably means that haskell-ghc-mod was activated twice for some reason? Not entirely sure. How did you manage to get ac-h to spew this nonsense I wonder?
