### ISSUE TITLE
trying to autocomplete when pressing space

### ISSUE THREAD

**Issue by davire** [atom-haskell/autocomplete-haskell#13]
Is it the normal behavior ? Seems annoying to me.

**Comment by lierdakil** [comment]
See http://flight-manual.atom.io/using-atom/sections/autocomplete/

TL;DR -- it's possible to disable this in autocomplete-plus settings (which is core package in Atom)

**Comment by davire** [comment]
This is atom 1.6.0 and autocomplete-plus 2.25.0. 

I don't see a setting that would prevent the suggestion to appear on a space keypress. On the other hand, there is a setting "minimum word length" set to "default: 3" that seems to be ignored. 

Depending on where I am in the source file (not inside a word), I get suggestion after pressing a single space or a single letter

![autocomplete](https://cloud.githubusercontent.com/assets/1065099/14052227/db44bdd4-f2c8-11e5-9ba7-d6f682ab8b52.gif)

**Comment by lierdakil** [comment]
Okay, so here's the option I was talking about:
![image](https://cloud.githubusercontent.com/assets/7275622/14056179/c218c46e-f2f9-11e5-8a2b-62ec27511dfe.png)

That said, this business with space seems a little bit unexpected. I'll see what I can do.

**Comment by lierdakil** [comment]
Okay, 0.6.4 should work as expected. Sorry I misunderstood you the first time around.
