### ISSUE TITLE
Bar at Bottom of Screen

### ISSUE THREAD

**Issue by severen** [atom-haskell/autocomplete-haskell#14]
Is there a way to get rid of this bar at the bottom of the screen? There seems to be no option to disable it.
![4u8vALG](http://i.imgur.com/4u8vALG.png)

**Comment by lierdakil** [comment]
'Haskell IDE -> Toggle completion hint panel' menu item. Although I should
probably add an option to hide it by default.

1 сент. 2016 г. 5:29 AM пользователь "Severen Redwood" <
notifications@github.com> написал:

**Comment by doersino** [comment]
What is it for, anyway? I can't seem to figure out what it does.

**Comment by lierdakil** [comment]
It shows type of last autocompleted expression. E.g. if you autocomplete `foldl`, it will look something like this:
![image](https://cloud.githubusercontent.com/assets/7275622/18182911/9505f2f2-709a-11e6-96df-a6329725ed36.png)
See atom-haskell/ide-haskell#99 for background and discussion.

**Comment by severen** [comment]
Shouldn't it be something that's in an ide-haskell type package?

I get the impression, and I imagine a lot of users do, that this package is simply an autocomplete-plus provider like most "autocomplete-" packages.

Regardless, I do think there should at least be a settings options that allows the user to disable it and its menu items.

**Comment by lierdakil** [comment]
At its core this package is still an ac+ provider. Completion hint panel was added as a band-aid for issue referenced above (although I found it very useful after the fact). Splitting completion hint panel into another package would add a whole lot of architectural and cognitive overhead with little to no tangible benefit.

I will add an option to control default visibility though, when I'm able.

**Comment by severen** [comment]
Thanks :)

**Comment by lierdakil** [comment]
Option to control default visibility added in 0.6.7. Bear in mind that visibility state is saved per-project (or rather, per directory), so this option only affects visibility on "new" projects.
