### ISSUE TITLE
Show data constructors in the autocomplete list when the user types `NameOfType.`

### ISSUE THREAD

**Issue by LukaHorvat** [atom-haskell/autocomplete-haskell#17]
I believe this would be a very nice feature to have. Not sure how easy it would be to implement.

So when I have a type like

```
data T = A | B | C
```

it's hard to remember what it's constructors are called. What I would like is to be able to type `T.` and have an autocomplete list with the constructors. Then when I select one and press enter the `T.` part would get replaced by the constructor.

If the constructors are a part of a qualified import then the `T.` part would be replaced with a qualified constructor name.

**Comment by lierdakil** [comment]
Sounds reasonable, and should be relatively straightforward to implement, although that would require ghc-mod-5.6.0.0 or higher (earlier versions don't output constructor-to-type associations)

I'm a bit concerned about using `.` as a separator though, since that's technically stealing syntax from module separator, and will end up being somewhat ambiguous. Maybe we could just show type constructors as a suggestions when type is autocompleted in non-type context (i.e. outside of type signature)?

**Comment by LukaHorvat** [comment]
Sounds good though it might make sense to have _some_ kind of a separator
that leaves only those constructors in the autocomplete list. Also, how do
you imagine the constructors would be indicated in the list?

**Comment by lierdakil** [comment]
With my suggestion it would probably something like this (note: `Prelude` import is qualified and aliased as `P` here):
![image](https://cloud.githubusercontent.com/assets/7275622/19397129/33d7c7a4-924f-11e6-8056-f73fb50b13d6.png)

**Comment by LukaHorvat** [comment]
Could be perhaps have a different marker for constructors?

**Comment by lierdakil** [comment]
That would be a bit complicated, but I'll see what I can do about that.

**Comment by LukaHorvat** [comment]
Awesome man!

**Comment by lierdakil** [comment]
Okay, something to this effect should be available with haskell-ghc-mod v1.18.0. Note that you _need_ ghc-mod 5.6 or above. Also 1.18.0 shows fully-qualified suggestions along with unqualified/alias-qualified ones and should work for aliased but unqualified imports as well (something that wasn't working before).

Constructors are shown as tags in completion panel -- it's a bit incorrect, possibly, but at least consistent with highlighting:
![image](https://cloud.githubusercontent.com/assets/7275622/19399602/096c1248-925b-11e6-8d48-65882855aff9.png)

There are probably some edge cases I missed where this will fail miserably, so feel free to report any bugs.
