### ISSUE TITLE
Typing "fun" to generate functions skeleton

### ISSUE THREAD

**Issue by andregpss** [atom-haskell/autocomplete-haskell#19]
Sorry for posting this as an issue. I did not see another proper place.

My question is: on the first gif (autocomplete), when the keyword "fun" is typed the function skeleton is generated. How can i do this?

**Comment by lierdakil** [comment]
That's a snippet. Snippets are [defined](https://github.com/atom-haskell/language-haskell/blob/master/snippets/language-haskell.cson) by language-haskell package (which is a dependency, so you should have that installed).

To expand a snippet, issue `snippets:expand` command. It's bound to `tab` by default. You can also choose the snippet in autocompletion list (it pops up automatically by default, or you can press `ctrl`+`space`):
![image](https://user-images.githubusercontent.com/7275622/27773961-227bee32-5f8f-11e7-89bc-f2f1ae1acdc4.png)

**Comment by andregpss** [comment]
Thanks. It is working!
