### ISSUE TITLE
Updating autocomplete-plus broke autocomplete-haskell on arch linux

### ISSUE THREAD

**Issue by jannickj** [atom-haskell/autocomplete-haskell#2]
After updating my autocomplete-plus I am no longer able to see the suggestions provided by autocomplete-haskell.

There itsn't any errors but there itsn't any suggestions either. 
I tested it on both mac and windows and it works fine. 

I wonder if there is some temporary files messing with my autocomplete-haskell but i doubt it, I also reinstalled everything just to make sure.
Are there any steps I can take to test if the dependencies of autocomplete-haskell is broken?

**Comment by lierdakil** [comment]
Do you mean specifically hoogle-powered hole-completions or any completions at all?

**Comment by jannickj** [comment]
any completions specific to haskell :S, meaning I still have the autocomplete completions but things like 
map showing ([a]->(a->b)->[b]) doesn't work.

**Comment by lierdakil** [comment]
Okay, does haskell-ghc-mod work? E.g. does `Haskell Ghc Mod: Type` show type for symbol under text cursor?

**Comment by jannickj** [comment]
Yes it does work

**Comment by lierdakil** [comment]
I found a bug, but not sure if it's related. Try v0.2.1. If it doesn't work, please check if
running

```
atom.packages.getActivePackage('autocomplete-haskell').mainModule.provider.editorMap.get(atom.workspace.getActiveEditor()).ghcmod
```

and

```
atom.packages.getActivePackage('autocomplete-haskell').mainModule.provider.editorMap.get(atom.workspace.getActiveEditor()).symbols
```

in console produces any meaningful output (`null`, `undefined` and `[]` do not count as such). You'll need to have haskell file open in your active editor.

**Comment by jannickj** [comment]
okay tested it: first one gives null and the second line gives me []. I did have some problems with atom where it said that I using 1.3 in one screen and 2.1 in another. I got it to show 2.1 everywhere by uninstalling and restarting it then installing it again. However I wonder if it actually did anything or if something stupid like file mod access is messing up my mods.
Is there some sort of method I can run to test the version?

**Comment by lierdakil** [comment]
If first one returns null, it means that either haskell-ghc-mod is not installed or not activated, or you're still using v0.2.0. Make sure you restarted Atom after update.

If there is file version inconsistency, I fear there is no way to tell which is which. Package is most likely installed in `~/.atom/packages/autocomplete-haskell/`. You may try to close Atom, remove this directory by hand, then run `apm install autocomplete-haskell` and start Atom again, see if it helps.

**Comment by lierdakil** [comment]
It's also possible that you're running older version of haskell-ghc-mod, that's incompatible with newer Atom versions, but then you probably would get errors. Anyway, please make sure that you're using at least v0.4.0

**Comment by jannickj** [comment]
I deleted the entire .atom folder just to make sure, it says I am running h-ghc-mod 0.42 and ac-h 0.2.1. However I am still getting null from that command call. 
When I get some free time first thing will be to learn atom modding and coffe script/javascript lol :p

**Comment by lierdakil** [comment]
Just to make sure, what version of Atom do you run?

**Comment by jannickj** [comment]
0.175 I for some reason had convinced myself that I recently had updated atom >< getting the newest version now

**Comment by jannickj** [comment]
Oh yes that was the problem >< wow sorry for wasting your time :/

**Comment by lierdakil** [comment]
I should teach myself to ask this question first, not last, since atom API is changing _fast_ and specifying required version is not supported yet...
