### ISSUE TITLE
Autocomplete pastes the whole signature of the autocompleted function

### ISSUE THREAD

**Issue by LukaHorvat** [atom-haskell/autocomplete-haskell#21]
With the newest update, pressing enter in the autocomplete list results in the whole signature being included.

For example `fmap<ENTER>` plops this into the editor `fmap :: Functor f => (a -> b) -> f a -> f b -- from:Functor` with a newline at the end.

**Comment by lierdakil** [comment]
Uh... that shouldn't be the case (also can't repoduce on my end). Did you update haskell-ghc-mod as well? Also do try to restart Atom, that might help?

**Comment by LukaHorvat** [comment]
Yep, everything is updated. I'm on the release channel of Atom at the moment so I'm running 1.19.

Here's a recording
https://dl.dropboxusercontent.com/s/0q6sszod04b09f2/2017-08-09_15-32-10.mp4

**Comment by lierdakil** [comment]
I think I might have an idea what's gone wrong. I have a vague recollection that you might be running on Windows?

**Comment by lierdakil** [comment]
If so, see if haskell-ghc-mod@v2.0.1 helps any.

**Comment by LukaHorvat** [comment]
I am on Windows but this didn't seem to help.

**Comment by lierdakil** [comment]
haskell-ghc-mod@v2.0.2 should hopefully help, although I'm not entirely sure what goes wrong here.

**Comment by LukaHorvat** [comment]
Hmm... Well, `fmap` now doesn't seem to appear in the autocomplete list (at least not as something autocomplete-haskell provides; only as an identifier already present in the file). 

Some other functions do appear in the list and autocomplete works for them.

Also, operator autocompletion doesn't work anymore.

**Comment by lierdakil** [comment]
See if v2.0.3 fixes that =\

**Comment by LukaHorvat** [comment]
Nope. Seems the same. It looks like all the Prelude identifiers don't show up. Very weird.

**Comment by lierdakil** [comment]
Well, I've found *a* problem, that should be fixed in v2.0.4, but I have doubts this will help at this point. I will try to debug on Windows ASAP, but that might take a while... Sincerely sorry about that.

**Comment by LukaHorvat** [comment]
Hey, no worries. I can live without autocomplete for a bit. Thank you for the amazing response time, as usual.

**Comment by LukaHorvat** [comment]
Err.... It works now? I don't know which version fixed it, but it works with 2.0.5.

**Comment by lierdakil** [comment]
Huh. Okay then, 2.0.4 actually helped I guess? Since 2.0.5 was an unrelated fix...
