### ISSUE TITLE
Completion hint panel should only appear for Haskell files

### ISSUE THREAD

**Issue by ncreep** [atom-haskell/autocomplete-haskell#6]
Hi,

I was surprised to see this empty panel appearing in Atom no matter what file/folder I was opening. Took me a bit of time to trace it back to `autocomplete-haskell`.

My question is, is it possible to make the panel appear only for Haskell source files?

Adding:

``` json
"activationHooks": [
   "language-haskell:grammar-used"
 ]
```

to the `package.json` file, works for non-Haskell folder (i.e. the panel doesn't appear), but when I try to open a Haskell folder, the whole editor hangs.

**Comment by lierdakil** [comment]
That's an interesting case. Apparently, `grammar-used` activation hook goes into a feedback loop, if package creates a text editor during activation. Probably should be reported to upstream.

Anyway, I found a workaround. It's somewhat clunky, but it should work. I'll push new version shortly.

**Comment by ncreep** [comment]
Thanks, it works now
