### ISSUE TITLE
Completion is sometimes too eager / zealous

### ISSUE THREAD

**Issue by dpercy** [atom-haskell/autocomplete-haskell#7]
When a local variable name is a substring of a top-level variable, the completion menu pops up and tries to complete the local variable (which I wanted to type) into the global variable (which I didn't).

Example:
I'm defining a very small function, so the argument name is one letter:
![screen shot 2015-11-12 at 1 14 54 am](https://cloud.githubusercontent.com/assets/349909/11111938/06702a22-88dc-11e5-9f92-4eb08832e018.png)

I want to type `x <Enter>` to insert the local variable and go to a new line.  Instead, when I type `x` the completion menu pops up:
![screen shot 2015-11-12 at 1 15 08 am](https://cloud.githubusercontent.com/assets/349909/11111964/4d209f9c-88dc-11e5-954a-ed3a734331fa.png)

and then pressing `<Enter>` accepts the completion:
![screen shot 2015-11-12 at 1 15 18 am](https://cloud.githubusercontent.com/assets/349909/11111983/6edc0108-88dc-11e5-9044-915e398bdf9c.png)

Usually when this happens it's because the local variable is one letter, but it can also happen with multi-letter variable names:
![screen shot 2015-11-12 at 1 18 18 am](https://cloud.githubusercontent.com/assets/349909/11112059/433b3720-88dd-11e5-85df-99ba99fafc9c.png)

It's possible to work around this by hitting `<Esc>` before `<Enter>`, but it's still frustrating because my muscle memory is expecting behavior closer to ghci or a plain text editor.

Some ideas for a solution:
1. Don't allow pressing `<Enter>` to accept a completion, since you can still use `<Tab>`.
2. Don't automatically pop up the menu, since you can still use `<Ctrl-Space>`.
3. Make idea 1 or idea 2 (or both) available as a configuration option.

**Comment by lierdakil** [comment]
autocomplete-haskell uses autocomplete-plus as a frontend. You can configure autocomplete-plus for both (1) and (2), so please see its settings.

**Comment by dpercy** [comment]
Oh, perfect.  Thank you!
