### ISSUE TITLE
Words from comments go to the autocompletion list

### ISSUE THREAD

**Issue by welf** [atom-haskell/autocomplete-haskell#8]
If I use a word in comments, it goes to the autocompletion list and creates an unnecessary noise in it. Is it possible not to parse comments and not to offer words from comments in autocompletion list? 

<img width="345" alt="func" src="https://cloud.githubusercontent.com/assets/1454462/11366009/82c49976-92bb-11e5-9095-743db4fc1a3d.png">

**Comment by lierdakil** [comment]
This is what Autocomplete-plus' default SymbolProvider does. I could outright suppress it, but that would stop _any_ suggestions from current file showing up. Which is not ideal. I'm not aware of any way to make SymbolProvider ignore some grammar spans (like comments). Note that you can disable default provider or blacklist it for certain scopes in autocomplete-plus settings.
